"""Validation rules for ProjectConfig.

Catalogs of valid values sourced from SMART-DEFAULTS-MATRIX.md.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cc_rig.config.project import ProjectConfig

# ---------------------------------------------------------------------------
# Valid value catalogs (from SMART-DEFAULTS-MATRIX.md §1)
# ---------------------------------------------------------------------------

VALID_LANGUAGES = {"python", "typescript", "go", "rust"}

VALID_FRAMEWORKS_BY_LANGUAGE: dict[str, set[str]] = {
    "python": {"fastapi", "django", "flask"},
    "typescript": {"nextjs"},
    "go": {"gin", "echo"},
    "rust": {"clap"},
}

VALID_FRAMEWORKS = {fw for fws in VALID_FRAMEWORKS_BY_LANGUAGE.values() for fw in fws}

VALID_WORKFLOWS = {"speedrun", "standard", "spec-driven", "gtd-lite", "verify-heavy"}

VALID_PROJECT_TYPES = {"api", "web_fullstack", "cli"}

VALID_PERMISSION_MODES = {"default", "permissive"}

VALID_CLAUDE_PLANS = {"pro", "team", "max", "enterprise"}

VALID_SDLC_PHASES = {
    "planning",
    "coding",
    "testing",
    "review",
    "security",
    "database",
    "devops",
    "",
}

# 12 core agents (§1a)
VALID_AGENTS = {
    "code-reviewer",
    "test-writer",
    "explorer",
    "architect",
    "refactorer",
    "pr-reviewer",
    "implementer",
    "pm-spec",
    "security-auditor",
    "doc-writer",
    "techdebt-hunter",
    "db-reader",
    # Add-on agent (generated by worktrees add-on)
    "parallel-worker",
}

# 19 commands (§1b)
VALID_COMMANDS = {
    "fix-issue",
    "review",
    "test",
    "plan",
    "learn",
    "assumptions",
    "remember",
    "refactor",
    "spec-create",
    "spec-execute",
    "techdebt",
    "security",
    "document",
    "optimize",
    "gtd-capture",
    "gtd-process",
    "daily-plan",
    "worktree",
}

# 14 hooks + 1 opt-in (§1c)
VALID_HOOKS = {
    "format",
    "lint",
    "typecheck",
    "block-rm-rf",
    "block-env",
    "block-main",
    "session-context",
    "stop-validator",
    "memory-stop",
    "memory-precompact",
    "push-review",
    "subagent-review",
    "commit-message",
    "doc-review",
    "autonomy-loop",
}

# Valid CC hook events (Appendix A of IMPLEMENTATION-PLAN.md)
VALID_CC_EVENTS = {
    "PreToolUse",
    "PostToolUse",
    "Stop",
    "SessionStart",
    "SessionEnd",
    "PreCompact",
    "SubagentStop",
    "UserPromptSubmit",
    "Notification",
}

# Valid CC tool names (Appendix B)
VALID_CC_TOOLS = {
    "Read",
    "Write",
    "Edit",
    "MultiEdit",
    "Bash",
    "Glob",
    "Grep",
    "WebSearch",
    "WebFetch",
    "Task",
    "TodoRead",
    "TodoWrite",
    "NotebookEdit",
}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_config(config: ProjectConfig) -> list[str]:
    """Validate a ProjectConfig. Returns a list of error strings (empty = valid)."""
    errors: list[str] = []

    # Required fields
    if not config.project_name:
        errors.append("project_name is required")
    if not config.language:
        errors.append("language is required")
    if not config.framework:
        errors.append("framework is required")
    if not config.workflow:
        errors.append("workflow is required")

    # Enum validation
    if config.language and config.language not in VALID_LANGUAGES:
        errors.append(f"unknown language: {config.language!r}")

    if config.framework and config.framework not in VALID_FRAMEWORKS:
        errors.append(f"unknown framework: {config.framework!r}")

    if config.language and config.framework:
        valid_for_lang = VALID_FRAMEWORKS_BY_LANGUAGE.get(config.language, set())
        if config.framework not in valid_for_lang:
            errors.append(
                f"framework {config.framework!r} is not valid for language {config.language!r}"
            )

    if config.workflow and config.workflow not in VALID_WORKFLOWS:
        errors.append(f"unknown workflow: {config.workflow!r}")

    if config.project_type and config.project_type not in VALID_PROJECT_TYPES:
        errors.append(f"unknown project_type: {config.project_type!r}")

    if config.permission_mode not in VALID_PERMISSION_MODES:
        errors.append(f"unknown permission_mode: {config.permission_mode!r}")

    if config.claude_plan not in VALID_CLAUDE_PLANS:
        errors.append(f"unknown claude_plan: {config.claude_plan!r}")

    # List membership validation
    for agent in config.agents:
        if agent not in VALID_AGENTS:
            errors.append(f"unknown agent: {agent!r}")

    for command in config.commands:
        if command not in VALID_COMMANDS:
            errors.append(f"unknown command: {command!r}")

    for hook in config.hooks:
        if hook not in VALID_HOOKS:
            errors.append(f"unknown hook: {hook!r}")

    # Mutual exclusivity
    if config.features.spec_workflow and config.features.gtd:
        errors.append(
            "features.spec_workflow and features.gtd cannot both be enabled — "
            "spec-workflow is plan-first, GTD is capture-first. Pick one."
        )

    # Feature flag implications
    if config.features.memory:
        if "memory-stop" not in config.hooks:
            errors.append("features.memory is True but 'memory-stop' not in hooks")
        if "memory-precompact" not in config.hooks:
            errors.append("features.memory is True but 'memory-precompact' not in hooks")
        if "remember" not in config.commands:
            errors.append("features.memory is True but 'remember' not in commands")

    if config.features.spec_workflow:
        if "pm-spec" not in config.agents:
            errors.append("features.spec_workflow is True but 'pm-spec' not in agents")
        if "implementer" not in config.agents:
            errors.append("features.spec_workflow is True but 'implementer' not in agents")
        if "spec-create" not in config.commands:
            errors.append("features.spec_workflow is True but 'spec-create' not in commands")
        if "spec-execute" not in config.commands:
            errors.append("features.spec_workflow is True but 'spec-execute' not in commands")

    if config.features.gtd:
        for cmd in ("gtd-capture", "gtd-process", "daily-plan"):
            if cmd not in config.commands:
                errors.append(f"features.gtd is True but {cmd!r} not in commands")

    if config.features.worktrees:
        if "parallel-worker" not in config.agents:
            errors.append("features.worktrees is True but 'parallel-worker' not in agents")
        if "worktree" not in config.commands:
            errors.append("features.worktrees is True but 'worktree' not in commands")

    # Skill validation
    for skill in config.recommended_skills:
        if skill.sdlc_phase and skill.sdlc_phase not in VALID_SDLC_PHASES:
            errors.append(f"skill {skill.name!r} has unknown sdlc_phase: {skill.sdlc_phase!r}")

    # Model override validation
    for agent_name in config.model_overrides:
        if agent_name not in VALID_AGENTS:
            errors.append(f"model_overrides references unknown agent: {agent_name!r}")

    return errors


def validate_config_warnings(config: ProjectConfig) -> list[str]:
    """Return non-fatal warnings for a ProjectConfig (empty = no warnings)."""
    warnings: list[str] = []
    return warnings
